// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: chat.grpc.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "chat";

export interface Member {
  username: string;
  avatar?: string | undefined;
  userId: string;
  lastReadAt?: string | undefined;
}

export interface CreateConversationRequest {
  type: string;
  members: Member[];
  groupName?: string | undefined;
  groupAvatar?: string | undefined;
  createrId?: string | undefined;
}

export interface CreateConversationResponse {
  conversation: Conversation | undefined;
}

export interface AddMemberToConversationRequest {
  conversationId: string;
  memberIds: string[];
}

export interface AddMemberToConversationResponse {
  status: string;
}

export interface GetConversationsRequest {
  userId: string;
  limit: string;
  page: string;
}

export interface Message {
  id: string;
  conversationId: string;
  senderId: string;
  text: string;
  replyToMessageId?: string | undefined;
  isDeleted: boolean;
  deleteType: string;
  createdAt: string;
  senderMember: SenderMember | undefined;
}

export interface ConversationMember {
  userId: string;
  /** timestamp (ms) */
  lastReadAt?: string | undefined;
  username?: string | undefined;
  avatar?: string | undefined;
}

export interface Conversation {
  id: string;
  type: string;
  unreadCount: string;
  groupName?: string | undefined;
  groupAvatar?: string | undefined;
  createdAt: string;
  updatedAt?: string | undefined;
  members: ConversationMember[];
  messages: Message[];
}

export interface GetConversationsResponse {
  conversations: Conversation[];
}

export interface GetMessagesRequest {
  conversationId: string;
  userId: string;
  limit: string;
  page: string;
}

export interface SenderMember {
  userId: string;
  username: string;
  avatar: string;
}

export interface GetMessagesResponse {
  messages: Message[];
}

export const CHAT_PACKAGE_NAME = "chat";

export interface ChatGrpcServiceClient {
  createConversation(request: CreateConversationRequest, metadata?: Metadata): Observable<CreateConversationResponse>;

  addMemberToConversation(
    request: AddMemberToConversationRequest,
    metadata?: Metadata,
  ): Observable<AddMemberToConversationResponse>;

  getConversations(request: GetConversationsRequest, metadata?: Metadata): Observable<GetConversationsResponse>;

  getMessagesByConversationId(request: GetMessagesRequest, metadata?: Metadata): Observable<GetMessagesResponse>;
}

export interface ChatGrpcServiceController {
  createConversation(
    request: CreateConversationRequest,
    metadata?: Metadata,
  ): Promise<CreateConversationResponse> | Observable<CreateConversationResponse> | CreateConversationResponse;

  addMemberToConversation(
    request: AddMemberToConversationRequest,
    metadata?: Metadata,
  ):
    | Promise<AddMemberToConversationResponse>
    | Observable<AddMemberToConversationResponse>
    | AddMemberToConversationResponse;

  getConversations(
    request: GetConversationsRequest,
    metadata?: Metadata,
  ): Promise<GetConversationsResponse> | Observable<GetConversationsResponse> | GetConversationsResponse;

  getMessagesByConversationId(
    request: GetMessagesRequest,
    metadata?: Metadata,
  ): Promise<GetMessagesResponse> | Observable<GetMessagesResponse> | GetMessagesResponse;
}

export function ChatGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createConversation",
      "addMemberToConversation",
      "getConversations",
      "getMessagesByConversationId",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_GRPC_SERVICE_NAME = "ChatGrpcService";
