// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: chat.grpc.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "chat";

export interface CreateConversationRequest {
  type: string;
  memberIds: string[];
  groupName?: string | undefined;
  groupAvatar?: string | undefined;
  createrId?: string | undefined;
}

export interface CreateConversationResponse {
  id: string;
  memberIds: string[];
  type: string;
  groupName?: string | undefined;
  groupAvatar?: string | undefined;
  adminId?: string | undefined;
}

export interface AddMemberToConversationRequest {
  conversationId: string;
  memberIds: string[];
}

export interface AddMemberToConversationResponse {
  status: string;
}

export const CHAT_PACKAGE_NAME = "chat";

export interface ChatGrpcServiceClient {
  createConversation(request: CreateConversationRequest, metadata?: Metadata): Observable<CreateConversationResponse>;

  addMemberToConversation(
    request: AddMemberToConversationRequest,
    metadata?: Metadata,
  ): Observable<AddMemberToConversationResponse>;
}

export interface ChatGrpcServiceController {
  createConversation(
    request: CreateConversationRequest,
    metadata?: Metadata,
  ): Promise<CreateConversationResponse> | Observable<CreateConversationResponse> | CreateConversationResponse;

  addMemberToConversation(
    request: AddMemberToConversationRequest,
    metadata?: Metadata,
  ):
    | Promise<AddMemberToConversationResponse>
    | Observable<AddMemberToConversationResponse>
    | AddMemberToConversationResponse;
}

export function ChatGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createConversation", "addMemberToConversation"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_GRPC_SERVICE_NAME = "ChatGrpcService";
