// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: chat.grpc.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "chat";

export interface GetMessageRequest {
}

export interface GetMessageResponse {
}

export const CHAT_PACKAGE_NAME = "chat";

export interface ChatGrpcServiceClient {
  getMessage(request: GetMessageRequest, metadata?: Metadata): Observable<GetMessageResponse>;
}

export interface ChatGrpcServiceController {
  getMessage(
    request: GetMessageRequest,
    metadata?: Metadata,
  ): Promise<GetMessageResponse> | Observable<GetMessageResponse> | GetMessageResponse;
}

export function ChatGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getMessage"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ChatGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CHAT_GRPC_SERVICE_NAME = "ChatGrpcService";
