// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: notification.grpc.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "notification";

export interface createNotificationRequest {
  inviterId: string;
  inviteeName: string;
  status: string;
}

export interface createNotificationResponse {
  id: string;
  userId: string;
  message: string;
  isRead: boolean;
  createdAt: Timestamp | undefined;
}

export const NOTIFICATION_PACKAGE_NAME = "notification";

export interface NotificationGrpcServiceClient {
  createNotification(request: createNotificationRequest, metadata?: Metadata): Observable<createNotificationResponse>;
}

export interface NotificationGrpcServiceController {
  createNotification(
    request: createNotificationRequest,
    metadata?: Metadata,
  ): Promise<createNotificationResponse> | Observable<createNotificationResponse> | createNotificationResponse;
}

export function NotificationGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createNotification"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("NotificationGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("NotificationGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const NOTIFICATION_GRPC_SERVICE_NAME = "NotificationGrpcService";
