// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface UserRegisterRequest {
  email: string;
  password: string;
  username: string;
}

export interface UserRegisterResponse {
  id: string;
  email: string;
  username: string;
}

export interface UserLoginRequest {
  email: string;
  password: string;
}

export interface UserLoginResponse {
  id: string;
  email: string;
  username: string;
  token: string;
}

export interface MakeFriendRequest {
  userId: string;
  friendEmail: string;
}

export interface MakeFriendResponse {
  status: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  register(request: UserRegisterRequest, metadata?: Metadata): Observable<UserRegisterResponse>;

  login(request: UserLoginRequest, metadata?: Metadata): Observable<UserLoginResponse>;

  makeFriend(request: MakeFriendRequest, metadata?: Metadata): Observable<MakeFriendResponse>;
}

export interface UserServiceController {
  register(
    request: UserRegisterRequest,
    metadata?: Metadata,
  ): Promise<UserRegisterResponse> | Observable<UserRegisterResponse> | UserRegisterResponse;

  login(
    request: UserLoginRequest,
    metadata?: Metadata,
  ): Promise<UserLoginResponse> | Observable<UserLoginResponse> | UserLoginResponse;

  makeFriend(
    request: MakeFriendRequest,
    metadata?: Metadata,
  ): Promise<MakeFriendResponse> | Observable<MakeFriendResponse> | MakeFriendResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login", "makeFriend"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
