// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: user.grpc.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface UpdateProfileRequest {
  fullName?: string | undefined;
  bio?: string | undefined;
  avatar?: Uint8Array | undefined;
  avatarFilename?: string | undefined;
  userId: string;
}

export interface UpdateProfileResponse {
  fullName?: string | undefined;
  bio?:
    | string
    | undefined;
  /** Trả về URL avatar mới */
  avatar?: string | undefined;
}

export interface UserRegisterRequest {
  email: string;
  password: string;
  username: string;
}

export interface UserRegisterResponse {
  id: string;
  email: string;
  username: string;
}

export interface UserLoginRequest {
  email: string;
  password: string;
}

export interface UserLoginResponse {
  id: string;
  email: string;
  username: string;
  avatar?: string | undefined;
  bio?: string | undefined;
  fullName: string;
  token: string;
}

export interface MakeFriendRequest {
  inviterId: string;
  inviteeEmail: string;
  inviterName: string;
}

export interface MakeFriendResponse {
  status: string;
}

export interface UpdateStatusRequest {
  inviteeId: string;
  status: string;
  inviterId: string;
  inviteeName: string;
}

export interface UpdateStatusResponse {
  status: string;
}

export interface Friend {
  id: string;
  email: string;
  username: string;
  avatar: string;
  fullName?: string | undefined;
}

export interface ListFriendsRequest {
  userId: string;
}

export interface ListFriendsResponse {
  friends: Friend[];
}

export interface DetailMakeFriendRequest {
  friendRequestId: string;
}

export interface FromUser {
  email: string;
  username: string;
  avatar: string;
  id: string;
  fullName: string;
}

export interface DetailMakeFriendResponse {
  id: string;
  fromUser: FromUser | undefined;
  toUserId: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetUserByIdRequest {
  userId: string;
}

export interface GetUserByIdResponse {
  fullName: string;
  username: string;
  email: string;
  bio: string;
  avatar: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserGrpcServiceClient {
  register(request: UserRegisterRequest, metadata?: Metadata): Observable<UserRegisterResponse>;

  login(request: UserLoginRequest, metadata?: Metadata): Observable<UserLoginResponse>;

  makeFriend(request: MakeFriendRequest, metadata?: Metadata): Observable<MakeFriendResponse>;

  updateStatusMakeFriend(request: UpdateStatusRequest, metadata?: Metadata): Observable<UpdateStatusResponse>;

  listFriends(request: ListFriendsRequest, metadata?: Metadata): Observable<ListFriendsResponse>;

  detailMakeFriend(request: DetailMakeFriendRequest, metadata?: Metadata): Observable<DetailMakeFriendResponse>;

  updateProfile(request: UpdateProfileRequest, metadata?: Metadata): Observable<UpdateProfileResponse>;

  getUserById(request: GetUserByIdRequest, metadata?: Metadata): Observable<GetUserByIdResponse>;
}

export interface UserGrpcServiceController {
  register(
    request: UserRegisterRequest,
    metadata?: Metadata,
  ): Promise<UserRegisterResponse> | Observable<UserRegisterResponse> | UserRegisterResponse;

  login(
    request: UserLoginRequest,
    metadata?: Metadata,
  ): Promise<UserLoginResponse> | Observable<UserLoginResponse> | UserLoginResponse;

  makeFriend(
    request: MakeFriendRequest,
    metadata?: Metadata,
  ): Promise<MakeFriendResponse> | Observable<MakeFriendResponse> | MakeFriendResponse;

  updateStatusMakeFriend(
    request: UpdateStatusRequest,
    metadata?: Metadata,
  ): Promise<UpdateStatusResponse> | Observable<UpdateStatusResponse> | UpdateStatusResponse;

  listFriends(
    request: ListFriendsRequest,
    metadata?: Metadata,
  ): Promise<ListFriendsResponse> | Observable<ListFriendsResponse> | ListFriendsResponse;

  detailMakeFriend(
    request: DetailMakeFriendRequest,
    metadata?: Metadata,
  ): Promise<DetailMakeFriendResponse> | Observable<DetailMakeFriendResponse> | DetailMakeFriendResponse;

  updateProfile(
    request: UpdateProfileRequest,
    metadata?: Metadata,
  ): Promise<UpdateProfileResponse> | Observable<UpdateProfileResponse> | UpdateProfileResponse;

  getUserById(
    request: GetUserByIdRequest,
    metadata?: Metadata,
  ): Promise<GetUserByIdResponse> | Observable<GetUserByIdResponse> | GetUserByIdResponse;
}

export function UserGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "register",
      "login",
      "makeFriend",
      "updateStatusMakeFriend",
      "listFriends",
      "detailMakeFriend",
      "updateProfile",
      "getUserById",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_GRPC_SERVICE_NAME = "UserGrpcService";
