// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: user.grpc.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface UserRegisterRequest {
  email: string;
  password: string;
  username: string;
}

export interface UserRegisterResponse {
  id: string;
  email: string;
  username: string;
}

export interface UserLoginRequest {
  email: string;
  password: string;
}

export interface UserLoginResponse {
  id: string;
  email: string;
  username: string;
  token: string;
}

export interface MakeFriendRequest {
  inviterId: string;
  inviteeEmail: string;
  inviterName: string;
}

export interface MakeFriendResponse {
  inviteeStatus: boolean;
  inviteeName: string;
  inviteeId: string;
}

export interface UpdateStatusRequest {
  inviteeId: string;
  status: string;
  inviterId: string;
}

export interface UpdateStatusResponse {
  status: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserGrpcServiceClient {
  register(request: UserRegisterRequest, metadata?: Metadata): Observable<UserRegisterResponse>;

  login(request: UserLoginRequest, metadata?: Metadata): Observable<UserLoginResponse>;

  makeFriend(request: MakeFriendRequest, metadata?: Metadata): Observable<MakeFriendResponse>;

  updateStatusMakeFriend(request: UpdateStatusRequest, metadata?: Metadata): Observable<UpdateStatusResponse>;
}

export interface UserGrpcServiceController {
  register(
    request: UserRegisterRequest,
    metadata?: Metadata,
  ): Promise<UserRegisterResponse> | Observable<UserRegisterResponse> | UserRegisterResponse;

  login(
    request: UserLoginRequest,
    metadata?: Metadata,
  ): Promise<UserLoginResponse> | Observable<UserLoginResponse> | UserLoginResponse;

  makeFriend(
    request: MakeFriendRequest,
    metadata?: Metadata,
  ): Promise<MakeFriendResponse> | Observable<MakeFriendResponse> | MakeFriendResponse;

  updateStatusMakeFriend(
    request: UpdateStatusRequest,
    metadata?: Metadata,
  ): Promise<UpdateStatusResponse> | Observable<UpdateStatusResponse> | UpdateStatusResponse;
}

export function UserGrpcServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["register", "login", "makeFriend", "updateStatusMakeFriend"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserGrpcService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_GRPC_SERVICE_NAME = "UserGrpcService";
